<h4>Cadastrar cliente</h4>
<form action="cliente-cadastrar-salvar" method="post">   
    <div class="form-group">
        <label>Nome do cliente: </label>        
        <input type="text" name="nome" class="form-control"> 
    </div>
    <div class="form-group">
        <label>E-mail: </label>    
        <input type="email" name="email" class="form-control"> 
    </div>
    <div class="form-group">
        <label>Descrição: </label>      
        <textarea name="descricao" id="descricao"></textarea>
    </div>    
    <button type="submit" class="btn btn-success">Cadastrar</button>
</form>