


<h4>Mande sua dúvida</h4>
<form action="material-cadastrar-salvar" method="post" enctype="multipart/form-data">   
    <div class="form-group">
        <label>Nome do material: </label>        
        <input type="text" name="nome" class="form-control"> 
    </div>
    <div class="form-group">
        <label>Descrição: </label>      
        <textarea name="descricao" id="descricao"></textarea>
    </div>
    <div class="form-group">
        <label>Categoria: </label>    
        <select class="form-control" name="categoria">
            <?php
            foreach ($this->view->categorias as $categoria) {
                echo "<option value='".$categoria["id_categoria"]."'>".$categoria["nome"]."</option>";
            }
            ?>          
            

        </select>
    </div>
    <div class="form-group">
        <label>imagem: </label>    
        <input type="file" name="imagem" class="form-control"> 
    </div>    
    <button type="submit" class="btn btn-success">Cadastrar</button>
</form>