



<h4>Relação de materiais</h4>
<table class="table table-striped table-hover table-bordered">
    <tr>        
        <td>Nome</td>
        <td>Descrição</td>
        <td>Categoria</td>
        <td>Imagem</td>
        <td>Ações</td>
    </tr> 
    <?php 
    /* $this->view->clientes é o array de clientes que foi passado pelo Controller, *após a excução do método select();
    * Através do foreach, é percorrido todo o array para fazer a impressão dos dados
    */ 
    foreach ($this->view->materiais as $material): 
    ?>
    <tr>
        <td><?php echo $material["nome_produto"]; ?></td>
        <td><?php echo $material["descricao"]; ?></td>
        <td><?php echo $material["id_categoria"]; ?></td>
        <td><?php echo $material["imagem"]; ?></td>
        <td>
            <a href="material-editar/<?php echo $material["id"]; ?>"><span class='glyphicon glyphicon-pencil'></span></a>
            <a href="material-deletar-confirmacao/<?php echo $material["id"]; ?>"><span class='glyphicon glyphicon-remove'></span></a>
        </td>
    </tr>
    <?php endforeach; ?>
</table>