<div class="jumbotron">
  <h1>Construir sem Grilos</h1>
  <p class="lead">Olá seja bem vindo ao Construir e Reformar sem Grilos, aqui você tira dúvidas sobre produtos que irá comprar ou de materiais já comprados</p>
  <p><a class="btn btn-lg btn-success" href="categorias" role="button">Vamos começar?</a></p>
</div>      
<div class="row">
  <div class="col-lg-4">
    <h2>Construir!</h2>
    <p>Você que vai começar a contruir um empreendimento novo e quer tirar dúvidas sobre os produtos que irá utilizar na sua obra aqui é o lugar para entender como funciona os materiais e aprender como usá-los sem desperdicio.</p>
    <p><a class="btn btn-primary" href="categorias" role="button">Clique aqui e veja mais detalhes &raquo;</a></p>
  </div>
  <div class="col-lg-4">
    <h2>Reformar</h2>
    <p>Para você que quer reformar seu empreendimento e que saber qual material usar e saber se o material indicado realmente é de acordo com a necessidade da obra!! aqui é o lugar para tirar essas dúvidas. </p>
    <p><a class="btn btn-primary" href="categorias" role="button">Clique aqui e saiba mais &raquo;</a></p>
  </div>
  <div class="col-lg-4">
    <h2>Esta na dúvida?</h2>
    <p>Você comprou um material indicado mas acha que ele não serve para sua construção ou reforma, e esta com a pulga atrás da orelha e acha que foi passado para tras tanto pelo construtor ou vendedor de material de construção, tire suas dúvidas aqui e veja se realmente o material é certo para sua obra.</p>
    <p><a class="btn btn-primary" href="categorias" role="button">Clique aqui e tire sua dúvida! &raquo;</a></p>
  </div>
</div>