<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="favicon.ico">

    <title>Construir e Reformar se Grilos</title>

    <!-- Bootstrap core CSS -->
    <link href="css/bootstrap.min.css" rel="stylesheet">
    <link href="css/style.css" rel="stylesheet">

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="assets/css/ie10-viewport-bug-workaround.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="justified-nav.css" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="assets/js/ie-emulation-modes-warning.js"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <div class="container">
      <div class="masthead"><picture>         
    <img srcset="image/logo.png" media="min-width: 300px">  
        <h3 class="text-muted">Construir e Reformar sem Grilos</h3></picture>
        <nav>
          <ul class="nav nav-justified">
            <li class="active"><a href="index">Home</a></li>
            <li><a href="produtos">Produtos</a></li>
            <li><a href="links">Links</a></li>
            <li><a href="contato">Contato</a></li>
          </ul>
        </nav>
      </div>

      <!-- Jumbotron -->
      <div class="jumbotron">
        <h1>Construir e Reformar sem Grilos</h1>
        <p class="lead">Olá seja bem vindo ao Construir e Reformar sem Grilos, aqui você tira dúvidas sobre produtos que irá comprar ou de materiais já comprados</p>
        <p><a class="btn btn-lg btn-success" href="produtos" role="button">Vamos começar?</a></p>
      </div>

      
      <div class="row">
        <div class="col-lg-4">
          <h2>Construir!</h2>
          <p>Você que vai começar a contruir um empreendimento novo e quer tirar dúvidas sobre os produtos que irá utilizar na sua obra aqui é o lugar para entender como funciona os materiais e aprender como usá-los sem desperdicio.</p>
          <p><a class="btn btn-primary" href="produtos" role="button">Clique aqui e veja mais detalhes &raquo;</a></p>
        </div>
        <div class="col-lg-4">
          <h2>Reformar</h2>
          <p>Para você que quer reformar seu empreendimento e que saber qual material usar e saber se o material indicado realmente é de acordo com a necessidade da obra!! aqui é o lugar para tirar essas dúvidas. </p>
          <p><a class="btn btn-primary" href="produtos" role="button">Clique aqui e saiba mais &raquo;</a></p>
       </div>
        <div class="col-lg-4">
          <h2>Esta na dúvida?</h2>
          <p>Você comprou um material indicado mas acha que ele não serve para sua construção ou reforma, e esta com a pulga atrás da orelha e acha que foi passado para tras tanto pelo construtor ou vendedor de material de construção, tire suas dúvidas aqui e veja se realmente o material é certo para sua obra.</p>
          <p><a class="btn btn-primary" href="produtos" role="button">Clique aqui e tire sua dúvida! &raquo;</a></p>
        </div>
      </div>

      <!-- Site footer -->
      <footer class="footer">
        <p>&copy; 2017 Paul Jackson.</p>
      </footer>

    </div> <!-- /container -->


    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>
  </body>
</html>
