
	<div class="container">
	<div class="row">
		<div class="col-md-12">
		<form method="POST" action="valida-login" id="form" name="form">
		<h1>Login</h1>
		  <div class="form-group">
			<label for="login">Login:</label>
			<input type="text" class="form-control" id="nome" name="nome">
		  </div>
		  <div class="form-group">
			<label for="senha">Senha:</label>
			<input type="password" class="form-control" id="senha" name="senha">
		  </div>
		  <button type="submit" class="btn btn-default">Entrar</button>
		</form>
		</div>
	</div>
</div>

