<h4>Editar categoria</h4>
<form action="/cate-editar-salvar/<?php echo $this->view->cates["id_categoria"]; ?>" method="post">    
    <div class="form-group">
        <label>Nome da categoria: </label>        
        <input type="text" name="nome" class="form-control" value="<?php echo $this->view->cates["nome"]; ?>" required> 
    </div>
  
    <button type="submit" class="btn btn-success">Editar</button>
</form>